---

#
# This role adds yum cron package and configuration. 
# We want this on any public facing OpenVZ installs so we 
# can pick up security updates. 
#

- name: install yum-cron
  yum: name=yum-cron state=present
  when: ansible_distribution == 'CentOS'

- name: install yum-cron.conf
  template: src=yum-cron.conf.j2 dest=/etc/yum/yum-cron.conf mode=0644
  when: ansible_distribution == 'CentOS'

- name: enable yum-cron
  copy: content="enable yum cron" dest=/var/lock/subsys/yum-cron mode=0644
  when: ansible_distribution == 'CentOS'
