---
# tasks to setup an http server

- name: copy the openvz mirror http config file
  template: src=eu-openvz-download.conf.j2 dest=/etc/httpd/conf.d/openvz-download.conf
  sudo: yes
  when: inventory_hostname == "eu.download.openvz.org"

- name: copy the openvz mirror http config file
  template: src=us-openvz-download.conf.j2 dest=/etc/httpd/conf.d/openvz-download.conf
  sudo: yes
  when: inventory_hostname == "us.download.openvz.org"

- name: copy the openvz mirror http config file
  template: src=download.conf.j2 dest=/etc/httpd/conf.d/download.conf
  sudo: yes
  when: inventory_hostname == "us.download.openvz.org"

- name: copy the openvz mirror http config file
  copy: src=types.conf dest=/etc/httpd/conf.d/types.conf
  sudo: yes

- name: remove "Welcome" config to enable indexing
  file: path="/etc/httpd/conf.d/welcome.conf" state=absent
  sudo: yes

- name: set apache running/enabled
  service: name=httpd enabled=yes
  notify: restart apache
  sudo: yes
