---
# tasks to setup a download server

- name: add upload group
  group: name=upload system=yes state=present

- name: add upload user
  user: name=upload home=/var/www/html comment="OpenVZ download server" createhome=yes system=yes

- name: add apache to upload group
  user: name=apache append=yes groups=upload

- name: copy the download http config file
  copy: src=download.conf dest=/etc/httpd/conf.d/download.conf

- name: copy the rsyncd config file
  copy: src=rsyncd.conf dest=/etc/rsyncd.conf

- name: copy the vsftpd config file
  copy: src=vsftpd.conf dest=/etc/vsftpd/vsftpd.conf
