---

- name: include variables
  include_vars: "../../download-mirror/vars/main.yml"

- name: add group
  group: name={{ download_group }} system=yes state=present
  sudo: yes

- name: add user
  user: name={{ download_user }} home={{ download_destination }} comment="OpenVZ download server" createhome=yes system=yes shell=/sbin/nologin
  sudo: yes

- name: change rights on directory
  command: chgrp -R download {{ download_destination }}
  sudo: yes
# FIXME
#  file:
#    path: "{{ jenkins_home }}/updates"
#    owner: "{{ jenkins_user }}"
#    group: "{{ jenkins_group }}"
#    mode: 0755
#    state: directory

# FIXME: add users accounts to /etc/passwd, /etc/group

- include: download-ftp.yml
- include: download-http.yml
- include: download-rsync.yml
