---
- name: ensure python-selinux is installed on all nodes.
  action: yum name=libselinux-python state=installed
  sudo: yes

- name: set selinux to permissive
  action: selinux policy=targeted state=permissive
  ignore_errors: True
  sudo: yes

- name: ensure selinux is turned off
  action: command /usr/sbin/setenforce 0
  ignore_errors: True
  sudo: yes
