---
# tasks to setup a vault server

- name: add vault group
  group: name=vault system=yes state=present

- name: add vault user
  user: name=vault-user home=/var/www/html/download.openvz.org comment="OpenVZ vault server" createhome=yes system=yes shell=/sbin/nologin

- name: add apache to vault group
  user: name=apache append=yes groups=vault

- name: remove "welcome" config to enable indexing
  file: path="/etc/httpd/conf.d/welcome.conf" state=absent

- name: configure apache service
  copy: src=vault.conf dest=/etc/httpd/conf.d/vault.conf
#  notify: restart apache
