---
# install apache(httpd)
- name: install apache
  yum: name={{ item }} state=present
  with_items:
  - httpd
  - httpd-tools

- name: set apache running/enabled
  service: name=httpd enabled=yes
  ignore_errors: true
  notify:
  - restart apache
  
# install hash randomization hotfix
- name: hotfix - copy over new httpd init script
  copy: src="{{ files }}/hotfix/httpd/httpd.init" dest=/etc/init.d/httpd
        owner=root group=root mode=0755
  notify:
  - restart apache
