---

- include: playbooks/docs.yml
- include: playbooks/download.yml
- include: playbooks/download-mirror.yml
- include: playbooks/forum.yml
- include: playbooks/git.yml
- include: playbooks/mail.yml
- include: playbooks/mirmon.yml
- include: playbooks/planet.yml
- include: playbooks/stats.yml
- include: playbooks/store.yml
- include: playbooks/vault.yml
- include: playbooks/wiki.yml
- include: playbooks/www.yml
