---

- name: install composer
  action: shell curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ creates=/usr/local/bin/composer.phar
  sudo: yes

- name: update composer
  action: shell /usr/local/bin/composer.phar self-update
  register: composer_update_output
  changed_when: composer_update_output.stdout.find('You are already using composer version') == -1
  sudo: yes

#- name: install packages for mediawiki extensions
#  yum: pkg={{item}}
#  with_items:
#  - liblua5.1-0
#  - ploticus

#- name: install php5-redis
#  yum: pkg=php5-redis force=yes state=present

- name: create mediawiki directory
  file: path={{ mediawiki_directory }} state=directory owner=mediawiki
  sudo: yes

- name: check out latest stable WMF branch of mediawiki
  git: repo=https://github.com/Orain/mediawiki-core.git
       dest="{{ mediawiki_directory }}"
       version=REL1_24
  sudo: yes
  sudo_user: mediawiki
#  notify:
#    - Rebuild localisation cache
#    - Update mediawiki
#    - Mediawiki submodule fileMode false

- name: check out extensions for mediawiki
  git: repo={{item.repo}}
       dest=/var/www/openvz-wiki/{{item.dest}}
       version={{item.version}}
  with_items: extensions
  sudo: yes
  sudo_user: mediawiki
#  notify:
#    - Rebuild localisation cache
#    - Update mediawiki
#    - Mediawiki submodule fileMode false

#- name: install dependencies for mediawiki extensions with composer
#  shell: cd /var/www/openvz-wiki/extensions/"{{item}}" && /usr/local/bin/composer.phar install
#  with_items:
#    - Validator

- name: check out skins for mediawiki
  git: repo={{item.repo}}
       dest=/var/www/openvz-wiki/{{item.dest}}
       version={{item.version}}
  with_items: skins
  sudo: yes
  sudo_user: mediawiki
#  notify:
#    - Mediawiki submodule fileMode false
