---

- name: create group mediawiki
  group: name={{ item }} state=present
  with_items:
  - mediawiki

- name: create user mediawiki
  user: name=mediawiki group=mediawiki shell=/sbin/nologin createhome=no

# This would perhaps be better named mediawiki-scripts?
#- name: create user "www-scripts"
#  user: name=www-scripts group=www-data shell=/bin/bash uid='2020'
