#- name: create group "mediawiki"
#  group: name={{item.name}} state=present
#  with_items:
#  - mediawiki
#  - mediawiki-ops

#- name: create user "mediawiki"
#  user: name=mediawiki group=mediawiki shell=/bin/bash

# This would perhaps be better named mediawiki-scripts?
#- name: create user "www-scripts"
#  user: name=www-scripts group=www-data shell=/bin/bash uid='2020'
