---
# tasks to setup a mirror server

- name: add openvz-mirror group
  group: name=openvz-mirror system=yes state=present

- name: add openvz-mirror user
  user: name=openvz-mirror home=/var/www/html/download.openvz.org comment="OpenVZ download server" createhome=yes system=yes

- name: add rsync to openvz-mirror group
  user: name=rsync append=yes groups=openvz-mirror

- name: install rsync package
  yum:  pkg={{item}} state=present
  with_items:
    - rsync

- name: copy the rsync config file
  copy: src=rsyncd.conf dest=/etc/rsyncd.conf

# FIXME: should be inetd or xinetd?
- name: set rsyncd running/enabled
  service: name=rsyncd enabled=yes
  ignore_errors: true
#  notify:
#  - restart rsyncd
