########################################
# Handlers for restarting services
#

- name: reload apache
  action: service name=httpd state=reloaded

- name: reload httpd
  action: service name=httpd state=reloaded

- name: restart crond
  action: service name=crond state=restarted

- name: restart iptables
  action: service name=iptables state=restarted

- name: restart ip6tables
  action: service name=ip6tables state=restarted

- name: restart mailman
  action: service name=mailman state=restarted

- name: restart ntpd
  action: service name=ntpd state=restarted

- name: restart rsyslog
  action: service name=rsyslog state=restarted

- name: restart sshd
  action: service name=sshd state=restarted

- name: restart network
  action: service name=network state=restarted

- name: restart dhcpd
  service: name=dhcpd state=restarted

- name: reload systemd
  command: systemctl daemon-reload
