---
- name: include variables
  include_vars: "apache.yml"

- name: install mod_ssl
  yum: pkg=mod_ssl state=installed
  sudo: yes

- name: update ssl.conf
  copy: src=ssl.conf dest=/etc/httpd/conf.d/ssl.conf owner=root group=root mode=644 backup=yes

- name: install certificate ssl intermediate cert
  copy: >
    src={{ ssl_chain }}
    dest=/etc/pki/tls/certs/{{ ssl_chain }}
    owner=root
    group=root
    mode=0644
  notify: restart apache
  sudo: yes

- name: install ssl certificate
  copy: >
    src={{ ssl_cert }}
    dest=/etc/pki/tls/certs/{{ ssl_cert }}
    owner=root
    group=root
    mode=0600
  notify: restart apache
  sudo: yes

- name: install ssl key
  copy: >
    src={{ ssl_key }}
    dest=/etc/pki/tls/private/{{ ssl_key }}
    owner=root
    group=root
    mode=0400
  notify: restart apache
  sudo: yes
