---

- name: use self-signed ssl certificate in case of stage servers
  include_vars: self-signed-ssl-certificate.yml
  when: ssl_chain is undefined

- name: define path to private ansible artifacts
  include_vars: ../../../../vars/global.yml

- name: install mod_ssl
  yum: pkg=mod_ssl state=installed
  sudo: yes

- name: update ssl.conf
  copy: src=ssl.conf dest=/etc/httpd/conf.d/ssl.conf owner=root group=root mode=644 backup=yes
  notify: restart apache
  sudo: yes

- name: install certificate ssl intermediate cert
  copy: >
    src={{ private }}/playbooks/roles/apache/files/{{ ssl_chain }}
    dest=/etc/pki/tls/certs/{{ ssl_chain }}
    owner=root
    group=root
    mode=0644
  notify: restart apache
  sudo: yes

- name: install ssl certificate
  copy: >
    src={{ private }}/playbooks/roles/apache/files/{{ item }}
    dest=/etc/pki/tls/certs/{{ ssl_cert }}
    owner=root
    group=root
    mode=0600
  with_items:
     - "{{ ssl_cert }}"
  notify: restart apache
  sudo: yes

- name: install ssl key
  copy: >
    src={{ private }}/playbooks/roles/apache/files/{{ item }}
    dest=/etc/pki/tls/private/{{ ssl_key }}
    owner=root
    group=root
    mode=0400
  with_items:
     - "{{ ssl_key }}"
  notify: restart apache
  sudo: yes
