---
- name: install apache
  yum: name={{ item }} state=present
  with_items:
  - httpd
  - httpd-tools

- name: set apache running/enabled
  service: name=httpd enabled=yes
  ignore_errors: true
  notify:
  - restart apache
