---
# tasks to setup a doc server
# see https://src.openvz.org/projects/OVZ/repos/vz-docs/browse/README.md

- name: add doc user
  user: name=doc-user home=/var/www/html comment="OpenVZ docs" createhome=yes system=yes

- name: add apache to docs group
  user: name=apache append=yes groups=doc-user

- name: install the doc packages
  yum:  pkg={{item}} state=present
  with_items:
    - asciidoc
    - fop
    - docbook5-style-xsl-extensions
    - docbook5-style-xsl
    - xerces-j2
    - docbook5-schemas

- name: install git package
  yum: name=git state=latest

- name: checkout git repo with sources
  git: repo=https://src.openvz.org/scm/ovz/vz-docs.git dest=/var/www/html/vz-docs

- name: setup crontab
  cron: name="publish doc" minute="00" job="cd /var/www/html/vz-docs && git pull && make && make publish"

- name: copy the download http config file
  copy: src=openvz-docs.conf dest=/etc/httpd/conf.d/openvz-docs.conf
