---
# tasks to setup a planet server
# see https://src.openvz.org/projects/OVZ/repos/openvz-planet/browse/README.md

- name: add planet group
  group: name=planet-user system=yes state=present

- name: add planet user
  user: name=planet-user home=/var/www/planet.openvz.org comment="People Planet Eater" system=yes shell=/sbin/nologin

- name: add apache to planet group
  user: name=apache append=yes groups=planet-user

- name: install the planet packages
  yum:  pkg={{item}} state=present
  with_items:
    - git

- name: checkout git repo with sources
  git: repo=https://src.openvz.org/scm/ovz/openvz-planet.git dest=/var/www/planet.openvz.org

- name: checkout git submodule
  command: git submodule update --init --recursive chdir=/var/www/planet.openvz.org
  #command: cd /var/www/planet.openvz.org/ && git submodule init

- name: setup crontab
  cron: name="update planet feeds" minute="00" job="cd /var/www/planet.openvz.org && git pull && make"

- name: copy the planet http config file
  copy: src=planet.conf dest=/etc/httpd/conf.d/planet.conf
