---
#
# Setup mysql server.
# https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/mariadb_server
#
- name: install mysql server packages
  yum: name={{ item }}  state=present
  with_items:
  - mysql-server

#- name: set kernel shared memory max to a larger value
#  sysctl: name=kernel.shmmax value={{ kernel_shmmax }}
#  when: kernel_shmmax is defined
#  notify:
#  - restart mysql

#- name: enable and start mysql database
#  service: name=mysql enabled=yes state=started

#- name: set mysql root user password
#  no_log: True
#  mysql_user: name=root password={{ mysql_root_password }} check_implicit_admin=true

#- name: copy my.cnf
#  copy: src={{ item }} dest=/etc/my.cnf owner=root group=root mode=0644
#  with_first_found:
#    - "{{ mariadb_config }}"
#    - my.cnf.default
#  notify:
#    - restart mysql

#- name: create .my.cnf file for future logins
#  template: src=dotmy.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0700

#- name: ensure mysql has a place to backup to
#  file: dest=/backups state=directory owner=mysql

#- name: copy over backup scriplet
#  copy: src=backup-database dest=/usr/local/bin/backup-database mode=0755

#- name: set up some cronjobs to backup databases as configured
#  cron: user=mysql name="Backup MySQL databases" minute="00" job="" cron_file=cron-backup-database-{{ item }}
#  with_items:
#  - "{{ dbs_to_backup }}"
#  sudo: yes
#  when: dbs_to_backup != []
