---
# tasks to setup a download mirror server with ftp access

- name: add openvz-mirror group
  group: name=openvz-mirror system=yes state=present

- name: add openvz-mirror user
  user: name=openvz-mirror home=/var/www/html/download.openvz.org/ comment="OpenVZ download server" createhome=yes system=yes

- name: install vsftpd package
  yum:  pkg={{item}} state=present
  with_items:
    - vsftpd

- name: add vsftpd to openvz-mirror group
  user: name=vsftpd append=yes groups=openvz-mirror

- name: copy the vsftpd config file
  copy: src=vsftpd.conf dest=/etc/vsftpd/vsftpd.conf

- name: set vsftpd running/enabled
  service: name=vsftpd enabled=yes
  ignore_errors: true
#  notify:
#  - restart vsftpd
