---
- hosts: wiki-criu
  roles:
    - common
    - apache
#    - mysql
    - mediawiki

  tasks:

  - name: install packages
    sudo: yes
    yum: name={{ item }} state=present
    with_items:
      - mysql
      - php

  - name: yum -y {{ yumcommand }}
    command: yum -y {{ yumcommand }}
    async: 7200
    poll: 15
