 ServerName	openvirtuozzo.org
 ServerAlias	*.openvirtuozzo.org
 ServerAlias	openvirtuozzo.net
 ServerAlias	*.openvirtuozzo.net
 ServerAlias	openvirtuozzo.com
 ServerAlias	*.openvirtuozzo.com

 ServerAlias	openvz.com
 ServerAlias	*. openvz.com
 ServerAlias	openvz.net
 ServerAlias	*. openvz.net

 ServerAlias	vzopen.org
 ServerAlias	*.vzopen.org
 ServerAlias	vzopen.net
 ServerAlias	*.vzopen.net
 ServerAlias	vzopen.com
 ServerAlias	*.vzopen.com

 ServerAlias	ovz.org
 ServerAlias	*.ovz.org

 ServerAdmin	kir@openvz.org
